class GameState:
    HOME = "home"
    PLAYING = "playing"
    TRANSITION = "transition"
    COMPLETED = "completed"
    LOST = "lost"
    WON = "won"
    LEVEL_WON = "level_won"
    HELP = "help"
    LOGIN = "login"
    LOGOUT = "logout"  
    ADMIN = "admin"
    LEADERBOARD = "leaderboard"
    NAME_INPUT = "name_input"
    RESET_PASSWORD = "reset_password"
